apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/kemoyar/argocdTask.git
        path: applications
        targetRevision: master
    destination:
        server: 'https://172.18.0.2:6443'
        namespace: default
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
