apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbooksecondcluster
    namespace: argocd
spec:
    project: second-project
    source:
        repoURL: https://github.com/kemoyar/argocdTask.git
        path: guestbookyamlfiles
        targetRevision: master
    destination:
        server: 'https://172.18.0.3:6443'
        namespace: default
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
